captainVersion: 4
services:
    # Homepage
    $$cap_appname:
        image: ghcr.io/benphelps/homepage:$$cap_homepage_version
        volumes:
            - $$cap_appname-config:/app/config
        caproverExtra:
            containerHttpPort: 3000
caproverOneClickApp:
    variables:
        - id: $$cap_homepage_version
          label: Homepage Version
          defaultValue: v0.6.16
          description: Check out their Docker page for the valid tags https://github.com/benphelps/homepage/pkgs/container/homepage
    instructions:
        start: >-
            A highly customizable homepage (or startpage / application dashboard) with Docker and service API integrations.
        end: >-
            Homepage has been successfully deployed!
            You can access the application at `http://$$cap_appname.$$cap_root_domain`.
    displayName: Homepage
    isOfficial: true
    description: A modern, secure, highly customizable application dashboard with integrations for more than 25 services and translations for over 15 languages. Easily configured via YAML files.
    documentation: Taken from https://github.com/benphelps/homepage
