captainVersion: 4
services:
    # Mixpost
    $$cap_appname:
        image: inovector/mixpost:$$cap_mixpost_version
        environment:
            APP_NAME: $$cap_mixpost_app_name
            APP_KEY: $$cap_mixpost_app_key
            APP_URL: https://$$cap_appname.$$cap_root_domain
            DB_DATABASE: $$cap_mariadb_name
            DB_USERNAME: $$cap_mariadb_username
            DB_PASSWORD: $$cap_mariadb_password
            DB_HOST: srv-captain--$$cap_appname-mariadb
            REDIS_HOST: srv-captain--$$cap_appname-redis
        depends_on:
            - $$cap_appname-mariadb
            - $$cap_appname-redis
        volumes:
            - $$cap_appname-storage:/var/www/html/storage/app
            - $$cap_appname-logs:/var/www/html/storage/logs
    # MariaDB
    $$cap_appname-mariadb:
        image: mariadb:$$cap_mariadb_version
        environment:
            MYSQL_RANDOM_ROOT_PASSWORD: '1'
            MYSQL_DATABASE: $$cap_mariadb_name
            MYSQL_USER: $$cap_mariadb_username
            MYSQL_PASSWORD: $$cap_mariadb_password
        volumes:
            - $$cap_appname-mariadb-data:/var/lib/mysql
        caproverExtra:
            notExposeAsWebApp: 'true'
    # Redis
    $$cap_appname-redis:
        image: redis:$$cap_redis_version
        caproverExtra:
            notExposeAsWebApp: 'true'
        volumes:
            - $$cap_appname-redis:/data
caproverOneClickApp:
    displayName: Mixpost
    description: Self-Hosted Social Media Management Software
    isOfficial: true
    documentation: https://mixpost.app
    instructions:
        start: |-
            Easily create, schedule, publish, and manage social media content in one place, with no limits or monthly subscription fees.
            It's the perfect social media management solution for bloggers, crafters and entrepreneurs.
        end: |-
            Mixpost has been successfully deployed! It might take few moments before it's fully started.
            You can access the application at `http://$$cap_appname.$$cap_root_domain`.
            Find the administrator login details in the logs.
    variables:
        - id: $$cap_mixpost_version
          label: Application | Version
          description: Mixpost version. Check out their valid tags at https://hub.docker.com/r/inovector/mixpost
          defaultValue: 'v1.1.3'
          validRegex: /.{1,}/
        - id: $$cap_redis_version
          label: Cache | Version
          description: Redis version. Check out their valid tags at https://hub.docker.com/_/redis/tags
          defaultValue: '7.0-alpine'
          validRegex: /.{1,}/
        - id: $$cap_mixpost_app_name
          label: Application | Name
          description: Name of the application.
          defaultValue: Mixpost
          validRegex: /.{1,}/
        - id: $$cap_mixpost_app_key
          label: Application | Key
          description: |-
              Base64 encoded application key for encryption.
              Use `https://generate-random.org/laravel-key-generator?count=1` to generate a key.
          defaultValue: base64:NWJzMXh3ZGl1bG9xZDc4c3NlejkzeXJudmd1ODJ0cWE=
          validRegex: /^([^\s^\/])+$/
        - id: $$cap_mariadb_version
          label: Database | Version
          description: MariaDB version. Check out their valid tags at https://hub.docker.com/_/mariadb/tags
          defaultValue: '10.7.8'
          validRegex: /.{1,}/
        - id: $$cap_mariadb_name
          label: Database | Name
          description: Name of the MariaDB database.
          defaultValue: mixpost
          validRegex: /^([^\s^\/])+$/
        - id: $$cap_mariadb_username
          label: Database | User Name
          description: Name of the MariaDB user.
          defaultValue: mixpost
          validRegex: /^([^\s^\/])+$/
        - id: $$cap_mariadb_password
          label: Database | User Password
          description: Password of the MariaDB user.
          defaultValue: $$cap_gen_random_hex(16)
          validRegex: /^([^\s^\/])+$/
